DEPTH:=..
SUBDIR:= 	alarm\
			bitset\
			FileHandling\
			HexPrinting\
			Integration\
			LALab12\
			LinuxVsWindowsThreadTest\
			MallocFree\
			ProgramExecutionTime\
			StringStream\
			LinuxFileSize

include rules.mk
