DEPTH:=..
SUBDIR:= 	alarm\
		bitset\
		FileHandling\
		HexPrinting\
		Integration\
		LALab12\
		LinuxVsWindowsThreadTest\
		MallocFree\
		ProgramExecutionTime\
		StringStream\
		LinuxFileSize\
		ArrayShift\
		VLI\
		VLI64bit\
		HighPrecisionTimer\
		Dynamic2DArray\
		SymmetricEncryption\
		LZ77\
		RadixTree

include rules.mk
