DEPTH = .

include openclsdkdefs.mk 

####
#
#  Targets
#
####

OPENCL			= 1
SAMPLE_EXE		= 1
EXE_TARGET 		= MatrixMultiplicationNaiveGPU
EXE_TARGET_INSTALL   	= MatrixMultiplicationNaiveGPU

####
#
#  C/CPP files
#
####

FILES 	= MatrixMultiplicationNaiveGPUMain MatrixMultiplicationNaiveGPU Timer
CLFILES	= MatrixMultiplicationNaiveGPU_Kernels.cl

include openclsdkrules.mk 

